In [1]:
import numpy
print(numpy.__version__)

1.26.4


In [3]:
import numpy as np
a=np.array
print(a)

<built-in function array>


In [5]:
a=np.array([7,8,18])
print(a)

[ 7  8 18]


In [11]:
b=np.array(list(map(int,input().split())))
print(b)

 3 4 5 2 5 6 7 78 8


[ 3  4  5  2  5  6  7 78  8]


In [23]:
a=np.array([[6,7,8],[1,4,0]])
print(a)
print(a.dtype) #data type check using ".dtype"
print(a.ndim) #dimensions os arrays using ".ndim"

[[6 7 8]
 [1 4 0]]
int32
2


In [29]:
a=np.array([1,2,3,4],str) #to convert data from one data type to another data type
print(a)

['1' '2' '3' '4']


In [37]:
a=np.array([[1,2,3,4,5,6]])
print(a.size) #size of an array using ".size"
print(a.shape) #rows and columns or shape of array)

6
(1, 6)


In [41]:
#shape of an array [rows & columns]
p=np.array([[1,2,3,4,5],[5,6,7,8,9],[0,1,2,3,4]])
print(p.shape)

(3, 5)


In [55]:
#reshaping an array using array.reshape(rows_num,col_num)
a=np.array([[1,2,3],[2,3,4]])
print("original array:\n",a)
print("shape:",a.shape)
b=a.reshape(3,2)
print("reshaped array:\n",b)

original array:
 [[1 2 3]
 [2 3 4]]
shape: (2, 3)
reshaped array:
 [[1 2]
 [3 2]
 [3 4]]


In [65]:
#slicing using numpy
a=np.array([[6,7,8],[4,5,7],[2,3,4]])
print(a,"\n")
print(a[0,1]) #array_name[row_num,col_num]

[[6 7 8]
 [4 5 7]
 [2 3 4]] 

7


In [78]:
#.max(),.min(),.sum()
a=np.array([1,2,3,4,556,6])
print(a)
print("Max:",a.max())
print("Min:",a.min())
print("sum:",a.sum())

[  1   2   3   4 556   6]
Max: 556
Min: 1
sum: 572


In [82]:
#identity matrix using .identity(rows_num)
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [84]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [86]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [104]:
#axis=0 -->columns
#axis=1 -->rows
a=np.array([[1,2],[3,4],[5,6]])
print(a)
print("max numbers in columns:",a.max(axis=0))
print("max numbers in rows:",a.max(axis=1))
print("sum of numbers in rows:",a.sum(axis=1))
print("sum of numbers in columns:",a.sum(axis=0))

[[1 2]
 [3 4]
 [5 6]]
max numbers in columns: [5 6]
max numbers in rows: [2 4 6]
sum of numbers in rows: [ 3  7 11]
sum of numbers in columns: [ 9 12]


In [106]:
#randn --> generates random number between (-1,0,1)
a=np.random.randn(3,4)
print(a)

[[-1.27664617  0.28291501 -0.69437948  0.89557096]
 [-1.22339829  1.07743342 -0.50605153  1.19617039]
 [-0.46799134 -0.18320918 -0.96939079 -0.63037742]]


In [114]:
#Arithmetic operations
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])
print("sum of a and b:\n",a+b)
print("product of a and b:\n",a*b)
print("division of a and b:\n",a/b)
print("subtraction of a and b:\n",a-b)

sum of a and b:
 [[ 8 10 12]
 [14 16 18]]
product of a and b:
 [[ 7 16 27]
 [40 55 72]]
division of a and b:
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]
subtraction of a and b:
 [[-6 -6 -6]
 [-6 -6 -6]]


In [23]:
#arange()--> similar to range
import numpy as np
print(np.arange(11))
print(np.arange(12).reshape(3,4))
print(np.arange(12)[1:8])
print(np.arange(12)[1:8][1])

[ 0  1  2  3  4  5  6  7  8  9 10]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[1 2 3 4 5 6 7]
2


In [19]:
a=np.arange(12).reshape(2,2,3)
print(a)
print(a[0][0][0])
print(a[0][0][1])
print(a[0][1][2])
print(a[0][1])

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
0
1
5
[3 4 5]


In [25]:
#Numpy BroadCasting
a=np.array([1,2,3,4,5,6,7])
b=np.array([2,4,6,8,10,12,14])
c=a*b
print(c)

[ 2  8 18 32 50 72 98]


In [43]:
a=np.array([[1,2,3,4],[2,4,5,6],[10,20,30,40]])
b=np.array([2,4,6,8])
print(a)
print(b)
print("\n")
print("Addition:")
print(a+b)
print("subtraction:")
print(a-b)
print("multiplication:")
print(a*b)
print("Division:")
print(a/b)

[[ 1  2  3  4]
 [ 2  4  5  6]
 [10 20 30 40]]
[2 4 6 8]


Addition:
[[ 3  6  9 12]
 [ 4  8 11 14]
 [12 24 36 48]]
subtraction:
[[-1 -2 -3 -4]
 [ 0  0 -1 -2]
 [ 8 16 24 32]]
multiplication:
[[  2   8  18  32]
 [  4  16  30  48]
 [ 20  80 180 320]]
Division:
[[0.5        0.5        0.5        0.5       ]
 [1.         1.         0.83333333 0.75      ]
 [5.         5.         5.         5.        ]]


In [49]:
a=np.arange(15).reshape(5,3)
print(a)
b=np.arange(5).reshape(5,1)
print(b)
print("\n")
print("Addition:\n",a+b)
print("Subtraction:\n",a-b)
print("Multiplication:\n",a*b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[0]
 [1]
 [2]
 [3]
 [4]]


Addition:
 [[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]
 [16 17 18]]
Subtraction:
 [[ 0  1  2]
 [ 2  3  4]
 [ 4  5  6]
 [ 6  7  8]
 [ 8  9 10]]
Multiplication:
 [[ 0  0  0]
 [ 3  4  5]
 [12 14 16]
 [27 30 33]
 [48 52 56]]


In [53]:
#Transpose
a=np.array([[1,2,3,7],[3,4,5,9],[4,5,6,7]])
print(a)
print("Transpose of matrix a:")
b=a.T #transpose
print(b)

[[1 2 3 7]
 [3 4 5 9]
 [4 5 6 7]]
Transpose of matrix a:
[[1 3 4]
 [2 4 5]
 [3 5 6]
 [7 9 7]]


In [57]:
a=np.array(["Bhargavi","Keerthana","Geethika"])
print(a)
b=np.array([["Bhargavi",2024],["Keerthana",2023],["Geethika",2024]])
print(b)

['Bhargavi' 'Keerthana' 'Geethika']
[['Bhargavi' '2024']
 ['Keerthana' '2023']
 ['Geethika' '2024']]


In [63]:
a=np.char.add(["Welcome"],["ToGuntur"])
b=np.char.multiply(a,3)
print(b)

['WelcomeToGunturWelcomeToGunturWelcomeToGuntur']


In [71]:
#around(array,decimalpoints) #floor #ceil
#Rounding function
a=np.array([12.24,90.12,12.546,52.85])
print(a)
print("Rounding Function:",np.around(a,1))
print("Floor Function:",np.floor(a))
print("Ceil Function:",np.ceil(a))

[12.24  90.12  12.546 52.85 ]
Rounding Function: [12.2 90.1 12.5 52.8]
Floor Function: [12. 90. 12. 52.]
Ceil Function: [13. 91. 13. 53.]


In [87]:
#mean() #median #average()
a=np.array([[1,2,3,7],[3,4,5,9],[4,5,6,7]])
print(a)
print("median:",np.median(a))
print("median:",np.median(a,0))
print("median:",np.median(a,1))
print("mean:",np.mean(a))
print("mean:",np.mean(a,0))
print("mean:",np.mean(a,1))
print("average:",np.average(a))
#Numpy has no attribute MODE

[[1 2 3 7]
 [3 4 5 9]
 [4 5 6 7]]
median: 4.5
median: [3. 4. 5. 7.]
median: [2.5 4.5 5.5]
mean: 4.666666666666667
mean: [2.66666667 3.66666667 4.66666667 7.66666667]
mean: [3.25 5.25 5.5 ]
average: 4.666666666666667


In [91]:
#dotproduct
a=np.array([[100,200],[30,40]])
b=np.array([[10,20],[50,60]])
print(a)
print(b)
print("Dot product:")
print(np.dot(a,b))

[[100 200]
 [ 30  40]]
[[10 20]
 [50 60]]
Dot product:
[[11000 14000]
 [ 2300  3000]]
